environment:
    version: 0.0.{build}

cache:
    - node_modules -> package.json

install:
    - npm install

build_script:
    - npm run lint
    - npm test
    - npm run build

for:
    - branches:
          only:
              - /release\/.*/
      after_build:

          - ps: >-
                "//registry.npmjs.org/:_authToken=$env:npm_auth_token`n" | out-file "$env:userprofile\.npmrc" -Encoding ASCII

          - npm publish --access public
